# .github/workflows/repository-metrics.yml
name: Repository Metrics
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'      # daily at midnight UTC
  workflow_dispatch: {}      # manual trigger

permissions:
  contents: write            # allow committing back to the repo
  actions: read              # allow running actions

jobs:
  generate-repo-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq docker.io

      - name: Generate repository metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}       # PAT with gist/repo scope
          base: ""                                # omit header
          plugin_repositories: yes                 # enable repositories plugin
          plugin_repositories_featured: iamAntimPal/MyGithubMaster  # focus on this repo
          plugin_repositories_limit: 5             # show up to 5 repos (if desired)

      - name: Commit and push metrics SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add metrics.plugin.repositories.svg
          git commit -m "chore: update repository metrics"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
