# .github/workflows/repository-metrics.yml
name: Repository Metrics
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'      # daily at midnight UTC
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read

jobs:
  generate-repo-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker and jq
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd containerd.io || true
          sudo apt-get autoremove -y || true
          sudo apt-get install -y docker.io jq
          sudo systemctl enable docker
          sudo systemctl start docker

      - name: Generate metrics and upload to Gist
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GIST }}  # Must have Gist scope
          filename: metrics.plugin.repositories.svg
          output_action: gist
          gist: 549db21ce1afaffa48994d7500d3d80b
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: iamAntimPal/MyGithubMaster
          plugin_repositories_limit: 5
          debug: yes
